export { default as alex } from './alex.jpeg'
export { default as eleanor } from './eleanor.jpeg'
export { default as ethan } from './ethan.jpeg'
export { default as kumar } from './kumar.jpeg'
export { default as maya } from './maya.jpeg'
